# NAME: Student CS178 Irina Golovko
# FILE: Makefile 
# DATE: August 28, 2018
# Desc: Makefile to build the HelloWorld program in c++.

	
# 'HelloWorld' is a target which depends on HelloWorld.cpp existing
HelloWorld: HelloWorld.cpp
	g++ -o HelloWorld HelloWorld.cpp

# target 'run' will launch the HelloWorld executable
run: HelloWorld
	./HelloWorld

# target 'clean' will do clean up:
# will delete the executable file and all the object files 
# from the directory  
clean: 
	rm HelloWorld 
	
